services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: filtering_system_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
